name: ep_forecasting_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - optuna
  - joblib
  - pytorch       
  - pip
  - pip:
    - import-ipynb  
    - shap          
    - rich         