name: ep_forecasting_env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - optuna
  - joblib
  - pytorch
  - torchvision
  - torchaudio
  - sqlite
  - ipython
  - ipykernel        
  - pip
  - pip:
    - import-ipynb
    - shap
    - rich