name: ep_forecasting_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - tensorflow
  - keras
  - pip
  #- import_ipynb can be only installed using pip (not conda) 
  - statsmodels
