name: ep_forecasting_env
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - scipy
  - optuna
  - joblib
  - pytorch
  - sqlite
  - ipython
  - ipykernel        
  - pip
  - pip:
    - import-ipynb
    - shap
    - rich